import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "mk" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations
const translations: Record<Language, Record<string, string>> = {
  mk: {
    // Navigation
    "nav.home": "Почетна",
    "nav.services": "Услуги",
    "nav.fleet": "Возен Парк",
    "nav.destinations": "Дестинации",
    "nav.reviews": "Рецензии",
    "nav.about": "За Нас",
    "nav.contact": "Контакт",
    "nav.book": "Резервирај",
    
    // Hero
    "hero.badge": "Премиум ВИП Превоз",
    "hero.title": "LuxTaxi",
    "hero.subtitle": "Македонија",
    "hero.description": "Луксузен такси превоз за туристи, бизнис клиенти и делегации низ Македонија и Балканот",
    "hero.tagline": "Симбол на елеганција, сигурност и врвна услуга",
    "hero.bookNow": "Резервирај Сега",
    "hero.viewDestinations": "Види Дестинации",
    "hero.licensedTransport": "Лиценциран Превоз",
    "hero.availability": "24/7 Достапност",
    "hero.professionalDrivers": "Професионални Шофери",
    
    // Services section (home)
    "services.label": "Наши Услуги",
    "services.title": "Премиум",
    "services.titleHighlight": "Превоз",
    "services.subtitle": "Од аеродромски трансфери до луксузни тури низ балканските метрополи",
    "services.allServices": "Сите Услуги",
    "services.vip.title": "ВИП Превоз",
    "services.vip.description": "Луксузен ВИП превоз од Битола со дискретен и искусен шофер, идеален за клиенти кои очекуваат највисоко ниво на услуга.",
    "services.corporate.title": "Корпоративен Транспорт",
    "services.corporate.description": "Обезбедуваме корпоративен транспорт за ИТ компании, странски фирми и деловни партнери. Точност и професионалност.",
    "services.delegations.title": "Превоз на Делегации",
    "services.delegations.description": "Транспорт на странски делегации и државни гости со највисоки стандарди за безбедност и репрезентативност.",
    "services.airport.title": "Аеродромски Трансфери",
    "services.airport.description": "Сигурен и луксузен аеродромски трансфер од Битола до сите балкански аеродроми. Навремено пристигнување, без стрес.",
    
    // Why Us section
    "whyUs.label": "Зошто Ние",
    "whyUs.title": "Зошто да",
    "whyUs.titleHighlight": "Не Одберете",
    "whyUs.subtitle": "Секое патување со нас е искуство на класа, прецизност и стил",
    "whyUs.drivers.title": "Професионални Шофери",
    "whyUs.drivers.description": "Искусни и дискретни шофери со познавање на сите рути низ Балканот.",
    "whyUs.punctuality.title": "Точност",
    "whyUs.punctuality.description": "Го следиме вашиот лет и секогаш сме навреме за пречек или испраќање.",
    "whyUs.safety.title": "Безбедност",
    "whyUs.safety.description": "Лиценцирани возила со редовен сервис и целосно осигурување.",
    "whyUs.terrain.title": "Познавање на Терен",
    "whyUs.terrain.description": "Ги знаеме сите патишта, алтернативни рути и локални совети.",
    "whyUs.prices.title": "Фиксни Цени",
    "whyUs.prices.description": "Транспарентен ценовник без скриени трошоци. Знаете колку плаќате.",
    "whyUs.support.title": "24/7 Поддршка",
    "whyUs.support.description": "Достапни сме во секое време за вашите резервации и прашања.",
    
    // CTA section
    "cta.title": "Подготвени сте за",
    "cta.titleHighlight": "патување?",
    "cta.description": "Контактирајте нè денес за резервација или понуда. Достапни сме 24/7 за вашите потреби.",
    "cta.callNow": "Јави се сега",
    "cta.contactForm": "Контакт форма",
    "cta.available": "Достапни 24/7",
    
    // Footer
    "footer.description": "Премиум такси услуги за туристи, бизнис клиенти и делегации низ Македонија и Балканот.",
    "footer.navigation": "Навигација",
    "footer.contact": "Контакт",
    "footer.followUs": "Следете Нè",
    "footer.waitingFee": "Чекање: 1 час = 400 ден.",
    "footer.rights": "Сите права задржани.",
    "footer.luxuryTransport": "Луксузен превоз од Битола до сите дестинации",
    "footer.location": "Битола, Македонија",
    "footer.availability": "24/7 достапност",

    // Services Page
    "servicesPage.label": "Наши Услуги",
    "servicesPage.title": "Премиум",
    "servicesPage.titleHighlight": "Услуги",
    "servicesPage.subtitle": "Од ВИП превоз до корпоративен транспорт - целосна палета на луксузни услуги",
    "servicesPage.vip.title": "ВИП и наменски превоз со професионален шофер",
    "servicesPage.vip.description": "LuxTaxi нуди луксузен ВИП превоз од Битола со дискретен и искусен шофер, идеален за клиенти кои очекуваат највисоко ниво на услуга. Нашите возила се нови, климатизирани и целосно опремени за комфорно патување.",
    "servicesPage.vip.feature1": "Дискретен и искусен шофер",
    "servicesPage.vip.feature2": "Нови, климатизирани возила",
    "servicesPage.vip.feature3": "Целосно опремени за комфор",
    "servicesPage.vip.feature4": "Идеално за индивидуални клиенти",
    "servicesPage.vip.feature5": "Совршено за туристи и деловни патувања",
    "servicesPage.corporate.title": "Корпоративен транспорт за бизниси и ИТ компании",
    "servicesPage.corporate.description": "Обезбедуваме корпоративен транспорт во Македонија за ИТ компании, странски фирми и деловни партнери. Точноста, професионалниот пристап и флексибилноста нè прават доверлив партнер за секој бизнис настан.",
    "servicesPage.corporate.feature1": "Транспорт за ИТ компании",
    "servicesPage.corporate.feature2": "Превоз на деловни партнери",
    "servicesPage.corporate.feature3": "Точност и професионалност",
    "servicesPage.corporate.feature4": "Флексибилни термини",
    "servicesPage.corporate.feature5": "Долгорочна соработка",
    "servicesPage.delegations.title": "Превоз на делегации и официјални гости",
    "servicesPage.delegations.description": "LuxTaxi е вистинскиот избор за транспорт на странски делегации и државни гости. Нашиот возен парк одговара на највисоките стандарди за безбедност и репрезентативност.",
    "servicesPage.delegations.feature1": "Транспорт на странски делегации",
    "servicesPage.delegations.feature2": "Превоз на државни гости",
    "servicesPage.delegations.feature3": "Највисоки стандарди за безбедност",
    "servicesPage.delegations.feature4": "Пречек на аеродром",
    "servicesPage.delegations.feature5": "Комплетна логистичка поддршка",
    "servicesPage.airport.title": "Аеродромски трансфери",
    "servicesPage.airport.description": "Нудиме сигурен и луксузен аеродромски трансфер од Битола до Скопје и обратно, идеален за туристи, бизнис клиенти и странски делегации. Со LuxTaxi, секогаш пристигнувате навреме.",
    "servicesPage.airport.feature1": "Трансфери до сите балкански аеродроми",
    "servicesPage.airport.feature2": "Следење на лет во реално време",
    "servicesPage.airport.feature3": "Навремено пристигнување",
    "servicesPage.airport.feature4": "Без стрес и компромис",
    "servicesPage.airport.feature5": "Грижа за секој детал",
    "servicesPage.cta.title": "Потребен ви е",
    "servicesPage.cta.titleHighlight": "превоз?",
    "servicesPage.cta.subtitle": "Контактирајте нè за резервација или понуда",
    "servicesPage.cta.button": "Резервирај Сега",

    // Fleet Page
    "fleetPage.label": "Возен Парк",
    "fleetPage.title": "Нашите",
    "fleetPage.titleHighlight": "Возила",
    "fleetPage.subtitle": "Модерни Volkswagen Passat возила, опремени со сè што ви треба за комфорно патување",
    "fleetPage.passengers": "4 патници",
    "fleetPage.climate": "Климатроник",
    "fleetPage.wireless": "Wireless",
    "fleetPage.seats": "Комфорни седишта",
    "fleetPage.luggage": "Голем багажник",
    "fleetPage.vehicle1.description": "Елегантен и моќен, идеален за бизнис патувања и аеродромски трансфери.",
    "fleetPage.vehicle2.description": "Луксузен кожен ентериер со клима, грејачи и најсовремена технологија.",
    "fleetPage.vehicle3.description": "Комфорно и безбедно патување низ прекрасните балкански предели.",
    "fleetPage.cta.title": "Резервирајте",
    "fleetPage.cta.titleHighlight": "денес",
    "fleetPage.cta.subtitle": "Изберете го вашето возило и започнете го патувањето со стил",
    "fleetPage.cta.button": "Резервирај Сега",

    // Destinations Page
    "destinationsPage.label": "Дестинации",
    "destinationsPage.title": "Цени и",
    "destinationsPage.titleHighlight": "Дестинации",
    "destinationsPage.subtitle": "Сите цени се од Битола до дестинацијата и обратно",
    "destinationsPage.searchPlaceholder": "Пребарувај дестинација...",
    "destinationsPage.destination": "Дестинација",
    "destinationsPage.price": "Цена",
    "destinationsPage.paymentMethods": "Начини на плаќање",
    "destinationsPage.cash": "Готовина",
    "destinationsPage.card": "Картица",
    "destinationsPage.invoice": "Фактура",
    "destinationsPage.discountTitle": "Попуст за авансно плаќање",
    "destinationsPage.discountText": "За сите резервации платени однапред (преку банкарска трансакција или картица), добивате 5% попуст на вкупната цена.",
    "destinationsPage.airports": "Аеродроми",
    "destinationsPage.borders": "Гранични Премини",
    "destinationsPage.greece": "Грција",
    "destinationsPage.serbia": "Србија",
    "destinationsPage.albania": "Албанија",
    "destinationsPage.bulgaria": "Бугарија",
    "destinationsPage.croatia": "Хрватска",
    "destinationsPage.montenegro": "Црна Гора",
    "destinationsPage.kosovo": "Косово",
    "destinationsPage.tourist": "Туристички Дестинации",
    "destinationsPage.cities": "Градови во Македонија",
    "destinationsPage.cta.title": "Резервирајте",
    "destinationsPage.cta.titleHighlight": "денес",
    "destinationsPage.cta.subtitle": "Контактирајте нè за резервација или понуда",
    "destinationsPage.cta.button": "Резервирај Сега",

    // About Page
    "aboutPage.label": "За Нас",
    "aboutPage.title": "Луксузен Такси",
    "aboutPage.titleHighlight": "Превоз",
    "aboutPage.subtitle": "Симбол на елеганција, сигурност и врвна услуга во премиум превозот низ Балканот",
    "aboutPage.stat1": "Години искуство",
    "aboutPage.stat2": "Задоволни клиенти",
    "aboutPage.stat3": "Дестинации",
    "aboutPage.stat4": "Достапност",
    "aboutPage.welcomeTitle": "Добредојдовте во",
    "aboutPage.welcomeTitleHighlight": "LuxTaxi Македонија",
    "aboutPage.welcomeText1": "Нашите модерни возила и професионални шофери овозможуваат незаборавно и безбедно патување, без разлика дали патувате кон аеродром, деловен состанок или вашата омилена туристичка дестинација.",
    "aboutPage.welcomeText2": "Од ВИП аеродромски трансфери, преку приватен превоз за деловни и дипломатски клиенти, до луксузни тури низ балканските метрополи – секое патување со нас е искуство на класа, прецизност и стил.",
    "aboutPage.welcomeText3": "Со седиште во Битола, ги покриваме сите дестинации низ Македонија и Балканот. Нашата мисија е да обезбедиме врвен комфорт и сигурност за секој патник.",
    "aboutPage.valuesLabel": "Наши Вредности",
    "aboutPage.valuesTitle": "Што нè",
    "aboutPage.valuesTitleHighlight": "издвојува",
    "aboutPage.safety.title": "Безбедност",
    "aboutPage.safety.description": "Безбедноста на нашите патници е наш приоритет. Лиценцирани возила со редовен сервис.",
    "aboutPage.punctuality.title": "Точност",
    "aboutPage.punctuality.description": "Секогаш сме навреме. Го следиме вашиот лет и се прилагодуваме на вашите потреби.",
    "aboutPage.professionalism.title": "Професионалност",
    "aboutPage.professionalism.description": "Нашите шофери се обучени за врвна услуга и дискреција. Секој детал е важен.",
    "aboutPage.dedication.title": "Посветеност",
    "aboutPage.dedication.description": "Секој клиент е важен. Се грижиме за вашето комфорно и пријатно патување.",
    "aboutPage.cta.title": "Започнете го патувањето",
    "aboutPage.cta.titleHighlight": "денес",
    "aboutPage.cta.subtitle": "Контактирајте нè за резервација или понуда",
    "aboutPage.cta.button": "Контакт",

    // Contact Page
    "contactPage.label": "Контакт",
    "contactPage.title": "Контактирајте",
    "contactPage.titleHighlight": "Нè",
    "contactPage.subtitle": "Резервирајте превоз или побарајте понуда - достапни сме 24/7",
    "contactPage.infoTitle": "Информации за",
    "contactPage.infoTitleHighlight": "контакт",
    "contactPage.phone": "Телефон",
    "contactPage.email": "Е-маил",
    "contactPage.location": "Локација",
    "contactPage.workingHours": "Работно време",
    "contactPage.availability": "24/7 достапност",
    "contactPage.callDirect": "Јави се директно",
    "contactPage.sendViber": "Испрати Viber порака",
    "contactPage.sendWhatsApp": "Испрати WhatsApp порака",
    "contactPage.urgentNote": "* За итни резервации, препорачуваме телефонски повик.",
    "contactPage.formTitle": "Испратете барање",
    "contactPage.nameLabel": "Име и презиме *",
    "contactPage.namePlaceholder": "Вашето име",
    "contactPage.phoneLabel": "Телефон *",
    "contactPage.phonePlaceholder": "+389 7X XXX XXX",
    "contactPage.emailLabel": "Е-маил",
    "contactPage.emailPlaceholder": "vash@email.com",
    "contactPage.destinationLabel": "Дестинација",
    "contactPage.destinationPlaceholder": "Каде патувате?",
    "contactPage.dateLabel": "Датум",
    "contactPage.messageLabel": "Порака",
    "contactPage.messagePlaceholder": "Дополнителни информации за вашето патување...",
    "contactPage.submitButton": "Испрати барање",
    "contactPage.submitting": "Се испраќа...",
    "contactPage.errorRequired": "Ве молиме внесете име и телефон.",
    "contactPage.successTitle": "Пораката е испратена!",
    "contactPage.successMessage": "Ќе ве контактираме наскоро.",
    "contactPage.errorTitle": "Грешка при испраќање",
    "contactPage.errorMessage": "Обидете се повторно или јавете се директно.",

    // Reviews Page
    "reviewsPage.label": "Рецензии",
    "reviewsPage.title": "Што велат нашите",
    "reviewsPage.titleHighlight": "клиенти",
    "reviewsPage.subtitle": "Прочитајте искуства од задоволни патници или споделете го вашето",
    "reviewsPage.formTitle": "Оставете ваша оцена",
    "reviewsPage.anonymous": "Анонимно",
    "reviewsPage.nameLabel": "Име *",
    "reviewsPage.namePlaceholder": "Вашето име",
    "reviewsPage.emailLabel": "Е-маил (опционално)",
    "reviewsPage.emailPlaceholder": "vash@email.com",
    "reviewsPage.ratingLabel": "Оцена",
    "reviewsPage.commentLabel": "Коментар *",
    "reviewsPage.commentPlaceholder": "Споделете го вашето искуство...",
    "reviewsPage.submitButton": "Испрати оцена",
    "reviewsPage.submitting": "Се испраќа...",
    "reviewsPage.approvalNote": "* Секоја оцена се одобрува пред да биде објавена.",
    "reviewsPage.errorComment": "Ве молиме напишете коментар.",
    "reviewsPage.errorName": "Ве молиме внесете име или изберете анонимно.",
    "reviewsPage.successTitle": "Благодариме!",
    "reviewsPage.successMessage": "Вашата оцена е примена и ќе биде објавена по одобрување.",
    "reviewsPage.errorTitle": "Грешка",
    "reviewsPage.errorMessage": "Обидете се повторно.",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.fleet": "Fleet",
    "nav.destinations": "Destinations",
    "nav.reviews": "Reviews",
    "nav.about": "About Us",
    "nav.contact": "Contact",
    "nav.book": "Book Now",
    
    // Hero
    "hero.badge": "Premium VIP Transport",
    "hero.title": "LuxTaxi",
    "hero.subtitle": "Macedonia",
    "hero.description": "Luxury taxi transport for tourists, business clients and delegations across Macedonia and the Balkans",
    "hero.tagline": "A symbol of elegance, safety and premium service",
    "hero.bookNow": "Book Now",
    "hero.viewDestinations": "View Destinations",
    "hero.licensedTransport": "Licensed Transport",
    "hero.availability": "24/7 Availability",
    "hero.professionalDrivers": "Professional Drivers",
    
    // Services section (home)
    "services.label": "Our Services",
    "services.title": "Premium",
    "services.titleHighlight": "Transport",
    "services.subtitle": "From airport transfers to luxury tours across Balkan metropolises",
    "services.allServices": "All Services",
    "services.vip.title": "VIP Transport",
    "services.vip.description": "Luxury VIP transport from Bitola with a discreet and experienced driver, ideal for clients who expect the highest level of service.",
    "services.corporate.title": "Corporate Transport",
    "services.corporate.description": "We provide corporate transport for IT companies, foreign firms and business partners. Punctuality and professionalism.",
    "services.delegations.title": "Delegation Transport",
    "services.delegations.description": "Transport of foreign delegations and state guests with the highest standards of security and representativeness.",
    "services.airport.title": "Airport Transfers",
    "services.airport.description": "Safe and luxurious airport transfer from Bitola to all Balkan airports. Timely arrival, stress-free.",
    
    // Why Us section
    "whyUs.label": "Why Us",
    "whyUs.title": "Why",
    "whyUs.titleHighlight": "Choose Us",
    "whyUs.subtitle": "Every journey with us is an experience of class, precision and style",
    "whyUs.drivers.title": "Professional Drivers",
    "whyUs.drivers.description": "Experienced and discreet drivers with knowledge of all routes across the Balkans.",
    "whyUs.punctuality.title": "Punctuality",
    "whyUs.punctuality.description": "We track your flight and are always on time for pickup or drop-off.",
    "whyUs.safety.title": "Safety",
    "whyUs.safety.description": "Licensed vehicles with regular service and full insurance.",
    "whyUs.terrain.title": "Local Knowledge",
    "whyUs.terrain.description": "We know all the roads, alternative routes and local tips.",
    "whyUs.prices.title": "Fixed Prices",
    "whyUs.prices.description": "Transparent pricing without hidden costs. You know what you pay.",
    "whyUs.support.title": "24/7 Support",
    "whyUs.support.description": "We are available at any time for your reservations and questions.",
    
    // CTA section
    "cta.title": "Ready for your",
    "cta.titleHighlight": "journey?",
    "cta.description": "Contact us today for a reservation or quote. We are available 24/7 for your needs.",
    "cta.callNow": "Call Now",
    "cta.contactForm": "Contact Form",
    "cta.available": "Available 24/7",
    
    // Footer
    "footer.description": "Premium taxi services for tourists, business clients and delegations across Macedonia and the Balkans.",
    "footer.navigation": "Navigation",
    "footer.contact": "Contact",
    "footer.followUs": "Follow Us",
    "footer.waitingFee": "Waiting: 1 hour = 400 MKD",
    "footer.rights": "All rights reserved.",
    "footer.luxuryTransport": "Luxury transport from Bitola to all destinations",
    "footer.location": "Bitola, Macedonia",
    "footer.availability": "24/7 availability",

    // Services Page
    "servicesPage.label": "Our Services",
    "servicesPage.title": "Premium",
    "servicesPage.titleHighlight": "Services",
    "servicesPage.subtitle": "From VIP transport to corporate transportation - a complete range of luxury services",
    "servicesPage.vip.title": "VIP and Private Transport with Professional Driver",
    "servicesPage.vip.description": "LuxTaxi offers luxury VIP transport from Bitola with a discreet and experienced driver, ideal for clients who expect the highest level of service. Our vehicles are new, air-conditioned and fully equipped for comfortable travel.",
    "servicesPage.vip.feature1": "Discreet and experienced driver",
    "servicesPage.vip.feature2": "New, air-conditioned vehicles",
    "servicesPage.vip.feature3": "Fully equipped for comfort",
    "servicesPage.vip.feature4": "Ideal for individual clients",
    "servicesPage.vip.feature5": "Perfect for tourists and business trips",
    "servicesPage.corporate.title": "Corporate Transport for Businesses and IT Companies",
    "servicesPage.corporate.description": "We provide corporate transport in Macedonia for IT companies, foreign firms and business partners. Punctuality, professional approach and flexibility make us a reliable partner for any business event.",
    "servicesPage.corporate.feature1": "Transport for IT companies",
    "servicesPage.corporate.feature2": "Business partner transport",
    "servicesPage.corporate.feature3": "Punctuality and professionalism",
    "servicesPage.corporate.feature4": "Flexible scheduling",
    "servicesPage.corporate.feature5": "Long-term cooperation",
    "servicesPage.delegations.title": "Transport of Delegations and Official Guests",
    "servicesPage.delegations.description": "LuxTaxi is the right choice for transport of foreign delegations and state guests. Our fleet meets the highest standards of safety and representativeness.",
    "servicesPage.delegations.feature1": "Transport of foreign delegations",
    "servicesPage.delegations.feature2": "State guest transport",
    "servicesPage.delegations.feature3": "Highest safety standards",
    "servicesPage.delegations.feature4": "Airport reception",
    "servicesPage.delegations.feature5": "Complete logistical support",
    "servicesPage.airport.title": "Airport Transfers",
    "servicesPage.airport.description": "We offer safe and luxurious airport transfer from Bitola to Skopje and back, ideal for tourists, business clients and foreign delegations. With LuxTaxi, you always arrive on time.",
    "servicesPage.airport.feature1": "Transfers to all Balkan airports",
    "servicesPage.airport.feature2": "Real-time flight tracking",
    "servicesPage.airport.feature3": "Timely arrival",
    "servicesPage.airport.feature4": "Stress-free and without compromise",
    "servicesPage.airport.feature5": "Attention to every detail",
    "servicesPage.cta.title": "Need a",
    "servicesPage.cta.titleHighlight": "ride?",
    "servicesPage.cta.subtitle": "Contact us for a reservation or quote",
    "servicesPage.cta.button": "Book Now",

    // Fleet Page
    "fleetPage.label": "Fleet",
    "fleetPage.title": "Our",
    "fleetPage.titleHighlight": "Vehicles",
    "fleetPage.subtitle": "Modern Volkswagen Passat vehicles, equipped with everything you need for a comfortable journey",
    "fleetPage.passengers": "4 passengers",
    "fleetPage.climate": "Climate Control",
    "fleetPage.wireless": "Wireless",
    "fleetPage.seats": "Comfortable Seats",
    "fleetPage.luggage": "Large Trunk",
    "fleetPage.vehicle1.description": "Elegant and powerful, ideal for business trips and airport transfers.",
    "fleetPage.vehicle2.description": "Luxurious leather interior with climate control, heaters and modern technology.",
    "fleetPage.vehicle3.description": "Comfortable and safe travel through beautiful Balkan landscapes.",
    "fleetPage.cta.title": "Book",
    "fleetPage.cta.titleHighlight": "today",
    "fleetPage.cta.subtitle": "Choose your vehicle and start your journey in style",
    "fleetPage.cta.button": "Book Now",

    // Destinations Page
    "destinationsPage.label": "Destinations",
    "destinationsPage.title": "Prices and",
    "destinationsPage.titleHighlight": "Destinations",
    "destinationsPage.subtitle": "All prices are from Bitola to destination and back",
    "destinationsPage.searchPlaceholder": "Search destination...",
    "destinationsPage.destination": "Destination",
    "destinationsPage.price": "Price",
    "destinationsPage.paymentMethods": "Payment Methods",
    "destinationsPage.cash": "Cash",
    "destinationsPage.card": "Card",
    "destinationsPage.invoice": "Invoice",
    "destinationsPage.discountTitle": "Discount for Advance Payment",
    "destinationsPage.discountText": "For all reservations paid in advance (via bank transfer or card), you receive a 5% discount on the total price.",
    "destinationsPage.airports": "Airports",
    "destinationsPage.borders": "Border Crossings",
    "destinationsPage.greece": "Greece",
    "destinationsPage.serbia": "Serbia",
    "destinationsPage.albania": "Albania",
    "destinationsPage.bulgaria": "Bulgaria",
    "destinationsPage.croatia": "Croatia",
    "destinationsPage.montenegro": "Montenegro",
    "destinationsPage.kosovo": "Kosovo",
    "destinationsPage.tourist": "Tourist Destinations",
    "destinationsPage.cities": "Cities in Macedonia",
    "destinationsPage.cta.title": "Book",
    "destinationsPage.cta.titleHighlight": "today",
    "destinationsPage.cta.subtitle": "Contact us for a reservation or quote",
    "destinationsPage.cta.button": "Book Now",

    // About Page
    "aboutPage.label": "About Us",
    "aboutPage.title": "Luxury Taxi",
    "aboutPage.titleHighlight": "Transport",
    "aboutPage.subtitle": "A symbol of elegance, safety and premium service in transport across the Balkans",
    "aboutPage.stat1": "Years of experience",
    "aboutPage.stat2": "Satisfied clients",
    "aboutPage.stat3": "Destinations",
    "aboutPage.stat4": "Availability",
    "aboutPage.welcomeTitle": "Welcome to",
    "aboutPage.welcomeTitleHighlight": "LuxTaxi Macedonia",
    "aboutPage.welcomeText1": "Our modern vehicles and professional drivers ensure an unforgettable and safe journey, whether you're traveling to an airport, business meeting, or your favorite tourist destination.",
    "aboutPage.welcomeText2": "From VIP airport transfers, through private transport for business and diplomatic clients, to luxury tours through Balkan metropolises – every journey with us is an experience of class, precision and style.",
    "aboutPage.welcomeText3": "Based in Bitola, we cover all destinations across Macedonia and the Balkans. Our mission is to provide top comfort and safety for every passenger.",
    "aboutPage.valuesLabel": "Our Values",
    "aboutPage.valuesTitle": "What makes us",
    "aboutPage.valuesTitleHighlight": "different",
    "aboutPage.safety.title": "Safety",
    "aboutPage.safety.description": "The safety of our passengers is our priority. Licensed vehicles with regular maintenance.",
    "aboutPage.punctuality.title": "Punctuality",
    "aboutPage.punctuality.description": "We are always on time. We track your flight and adapt to your needs.",
    "aboutPage.professionalism.title": "Professionalism",
    "aboutPage.professionalism.description": "Our drivers are trained for top service and discretion. Every detail matters.",
    "aboutPage.dedication.title": "Dedication",
    "aboutPage.dedication.description": "Every client is important. We care for your comfortable and pleasant journey.",
    "aboutPage.cta.title": "Start your journey",
    "aboutPage.cta.titleHighlight": "today",
    "aboutPage.cta.subtitle": "Contact us for a reservation or quote",
    "aboutPage.cta.button": "Contact",

    // Contact Page
    "contactPage.label": "Contact",
    "contactPage.title": "Contact",
    "contactPage.titleHighlight": "Us",
    "contactPage.subtitle": "Book transport or request a quote - we are available 24/7",
    "contactPage.infoTitle": "Contact",
    "contactPage.infoTitleHighlight": "Information",
    "contactPage.phone": "Phone",
    "contactPage.email": "Email",
    "contactPage.location": "Location",
    "contactPage.workingHours": "Working Hours",
    "contactPage.availability": "24/7 availability",
    "contactPage.callDirect": "Call Directly",
    "contactPage.sendViber": "Send Viber Message",
    "contactPage.sendWhatsApp": "Send WhatsApp Message",
    "contactPage.urgentNote": "* For urgent reservations, we recommend a phone call.",
    "contactPage.formTitle": "Send a Request",
    "contactPage.nameLabel": "Full Name *",
    "contactPage.namePlaceholder": "Your name",
    "contactPage.phoneLabel": "Phone *",
    "contactPage.phonePlaceholder": "+389 7X XXX XXX",
    "contactPage.emailLabel": "Email",
    "contactPage.emailPlaceholder": "your@email.com",
    "contactPage.destinationLabel": "Destination",
    "contactPage.destinationPlaceholder": "Where are you traveling?",
    "contactPage.dateLabel": "Date",
    "contactPage.messageLabel": "Message",
    "contactPage.messagePlaceholder": "Additional information about your trip...",
    "contactPage.submitButton": "Send Request",
    "contactPage.submitting": "Sending...",
    "contactPage.errorRequired": "Please enter your name and phone number.",
    "contactPage.successTitle": "Message Sent!",
    "contactPage.successMessage": "We will contact you soon.",
    "contactPage.errorTitle": "Error Sending",
    "contactPage.errorMessage": "Please try again or call us directly.",

    // Reviews Page
    "reviewsPage.label": "Reviews",
    "reviewsPage.title": "What our",
    "reviewsPage.titleHighlight": "clients say",
    "reviewsPage.subtitle": "Read experiences from satisfied passengers or share your own",
    "reviewsPage.formTitle": "Leave Your Review",
    "reviewsPage.anonymous": "Anonymous",
    "reviewsPage.nameLabel": "Name *",
    "reviewsPage.namePlaceholder": "Your name",
    "reviewsPage.emailLabel": "Email (optional)",
    "reviewsPage.emailPlaceholder": "your@email.com",
    "reviewsPage.ratingLabel": "Rating",
    "reviewsPage.commentLabel": "Comment *",
    "reviewsPage.commentPlaceholder": "Share your experience...",
    "reviewsPage.submitButton": "Submit Review",
    "reviewsPage.submitting": "Sending...",
    "reviewsPage.approvalNote": "* Each review is approved before being published.",
    "reviewsPage.errorComment": "Please write a comment.",
    "reviewsPage.errorName": "Please enter your name or choose anonymous.",
    "reviewsPage.successTitle": "Thank you!",
    "reviewsPage.successMessage": "Your review has been received and will be published after approval.",
    "reviewsPage.errorTitle": "Error",
    "reviewsPage.errorMessage": "Please try again.",
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("luxtaxi-language");
    return (saved as Language) || "mk";
  });

  useEffect(() => {
    localStorage.setItem("luxtaxi-language", language);
    document.documentElement.lang = language === "mk" ? "mk" : "en";
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
