// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.1";

// src/lib/mcp/tools/get-destinations.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/data/destinations.ts
var destinationCategories = [
  {
    id: "airports",
    nameKey: "destinationsPage.airports",
    isForeign: false,
    destinations: [
      { nameMk: "\u0410\u0442\u0438\u043D\u0430", nameEn: "Athens", priceMkd: null, priceEur: "400 \u20AC" },
      { nameMk: "\u0411\u0435\u043B\u0433\u0440\u0430\u0434", nameEn: "Belgrade", priceMkd: null, priceEur: "370 \u20AC" },
      { nameMk: "\u041E\u0445\u0440\u0438\u0434", nameEn: "Ohrid", priceMkd: "3300 \u0434\u0435\u043D", priceEur: "55 \u20AC" },
      { nameMk: "\u0421\u043A\u043E\u043F\u0458\u0435", nameEn: "Skopje", priceMkd: "5500 \u0434\u0435\u043D", priceEur: "90 \u20AC" },
      { nameMk: "\u0421\u043E\u043B\u0443\u043D", nameEn: "Thessaloniki", priceMkd: null, priceEur: "150 \u20AC" },
      { nameMk: "\u0421\u043E\u0444\u0438\u0458\u0430", nameEn: "Sofia", priceMkd: null, priceEur: "250 \u20AC" },
      { nameMk: "\u0422\u0438\u0440\u0430\u043D\u0430", nameEn: "Tirana", priceMkd: null, priceEur: "150 \u20AC" }
    ]
  },
  {
    id: "borders",
    nameKey: "destinationsPage.borders",
    isForeign: false,
    destinations: [
      { nameMk: "\u0411\u043B\u0430\u0446\u0435", nameEn: "Blace", priceMkd: "6300 \u0434\u0435\u043D", priceEur: "100 \u20AC" },
      { nameMk: "\u0411\u043E\u0433\u043E\u0440\u043E\u0434\u0438\u0446\u0430", nameEn: "Bogorodica", priceMkd: "5500 \u0434\u0435\u043D", priceEur: "90 \u20AC" },
      { nameMk: "\u0414\u0435\u0432\u0435 \u0411\u0430\u0438\u0440", nameEn: "Deve Bair", priceMkd: "7200 \u0434\u0435\u043D", priceEur: "115 \u20AC" },
      { nameMk: "\u041C\u0435\u045F\u0438\u0442\u043B\u0438\u0458\u0430 / \u0424\u0440\u0438\u0448\u043E\u043F", nameEn: "Medzitlija / Free Shop", priceMkd: "600/900 \u0434\u0435\u043D", priceEur: "10/15 \u20AC" },
      { nameMk: "\u041D\u043E\u0432\u043E \u0421\u0435\u043B\u043E", nameEn: "Novo Selo", priceMkd: "6500 \u0434\u0435\u043D", priceEur: "105 \u20AC" },
      { nameMk: "\u0421\u0442\u0435\u045A\u0435", nameEn: "Stenje", priceMkd: "1700 \u0434\u0435\u043D", priceEur: "28 \u20AC" },
      { nameMk: "\u0422\u0430\u0431\u0430\u043D\u043E\u0432\u0446\u0435", nameEn: "Tabanovce", priceMkd: "6000 \u0434\u0435\u043D", priceEur: "95 \u20AC" },
      { nameMk: "\u041A\u0430\u0444\u0430\u0441\u0430\u043D", nameEn: "Kafasan", priceMkd: "3800 \u0434\u0435\u043D", priceEur: "60 \u20AC" }
    ]
  },
  {
    id: "greece",
    nameKey: "destinationsPage.greece",
    isForeign: true,
    destinations: [
      { nameMk: "\u0410\u043C\u0438\u043D\u0434\u0435\u043E", nameEn: "Amyndeo", priceEur: "60 \u20AC" },
      { nameMk: "\u0410\u0441\u043F\u0440\u043E\u0432\u0430\u043B\u0442\u0430", nameEn: "Asprovalta", priceEur: "170 \u20AC" },
      { nameMk: "\u0410\u0442\u0438\u043D\u0430", nameEn: "Athens", priceEur: "400 \u20AC" },
      { nameMk: "\u0412\u0435\u0440\u0438\u0458\u0430", nameEn: "Veria", priceEur: "100 \u20AC" },
      { nameMk: "\u0412\u043E\u0434\u0435\u043D", nameEn: "Edessa", priceEur: "90 \u20AC" },
      { nameMk: "\u0412\u043E\u043B\u043E\u0441", nameEn: "Volos", priceEur: "190 \u20AC" },
      { nameMk: "\u0412\u0440\u0430\u0445\u043E\u0441", nameEn: "Vrahos", priceEur: "200 \u20AC" },
      { nameMk: "\u0413\u0440\u0435\u0432\u0435\u043D\u0430", nameEn: "Grevena", priceEur: "100 \u20AC" },
      { nameMk: "\u0418\u0433\u0443\u043C\u0435\u043D\u0438\u0446\u0430", nameEn: "Igoumenitsa", priceEur: "180 \u20AC" },
      { nameMk: "\u0408\u0430\u043D\u0438\u043D\u0430", nameEn: "Ioannina", priceEur: "160 \u20AC" },
      { nameMk: "\u041A\u0430\u0432\u0430\u043B\u0430", nameEn: "Kavala", priceEur: "220 \u20AC" },
      { nameMk: "\u041A\u0430\u043B\u0438\u0442\u0435\u0430", nameEn: "Kallithea", priceEur: "170 \u20AC" },
      { nameMk: "\u041A\u0430\u0442\u0435\u0440\u0438\u043D\u0438", nameEn: "Katerini", priceEur: "130 \u20AC" },
      { nameMk: "\u041A\u043E\u0436\u0430\u043D\u0438", nameEn: "Kozani", priceEur: "90 \u20AC" },
      { nameMk: "\u041A\u043E\u0441\u0442\u0443\u0440", nameEn: "Kastoria", priceEur: "100 \u20AC" },
      { nameMk: "\u041B\u0430\u0440\u0438\u0441\u0430", nameEn: "Larissa", priceEur: "140 \u20AC" },
      { nameMk: "\u041B\u0435\u043F\u0442\u043E\u043A\u0430\u0440\u0438\u0458\u0430", nameEn: "Leptokarya", priceEur: "150 \u20AC" },
      { nameMk: "\u041B\u0435\u0440\u0438\u043D", nameEn: "Florina", priceEur: "45 \u20AC" },
      { nameMk: "\u041B\u0435\u0444\u043A\u0430\u0434\u0430", nameEn: "Lefkada", priceEur: "220 \u20AC" },
      { nameMk: "\u041B\u0443\u0442\u0440\u0430\u043A\u0438", nameEn: "Loutraki", priceEur: "90 \u20AC" },
      { nameMk: "\u041C\u0435\u0442\u0435\u043E\u0440\u0438", nameEn: "Meteora", priceEur: "140 \u20AC" },
      { nameMk: "\u041D\u0435\u0430\u0432\u0440\u0430\u0441\u043D\u0430", nameEn: "Nea Vrasna", priceEur: "170 \u20AC" },
      { nameMk: "\u041D\u0435\u0430\u043F\u043E\u0440\u0438", nameEn: "Nea Peramos", priceEur: "170 \u20AC" },
      { nameMk: "\u041D\u0438\u043A\u0438\u0442\u0438", nameEn: "Nikiti", priceEur: "170 \u20AC" },
      { nameMk: "\u041F\u0430\u0459\u0443\u0440\u0438", nameEn: "Paliouri", priceEur: "190 \u20AC" },
      { nameMk: "\u041F\u0430\u0440\u0430\u043B\u0438\u0458\u0430", nameEn: "Paralia", priceEur: "130 \u20AC" },
      { nameMk: "\u041F\u0430\u0440\u0433\u0430", nameEn: "Parga", priceEur: "200 \u20AC" },
      { nameMk: "\u041F\u043E\u043B\u0438\u0445\u0440\u043E\u043D\u043E", nameEn: "Polychrono", priceEur: "170 \u20AC" },
      { nameMk: "\u041F\u0442\u043E\u043B\u0435\u043C\u0430\u0438\u0434\u0430", nameEn: "Ptolemaida", priceEur: "80 \u20AC" },
      { nameMk: "\u0421\u0430\u0440\u0442\u0438", nameEn: "Sarti", priceEur: "180 \u20AC" },
      { nameMk: "\u0421\u043E\u043B\u0443\u043D", nameEn: "Thessaloniki", priceEur: "150 \u20AC" },
      { nameMk: "\u0421\u0442\u0430\u0432\u0440\u043E\u0441", nameEn: "Stavros", priceEur: "200 \u20AC" },
      { nameMk: "\u0422\u043E\u0440\u043E\u043D\u0438", nameEn: "Toroni", priceEur: "190 \u20AC" },
      { nameMk: "\u0423\u0440\u0430\u043D\u043E\u0443\u043F\u043E\u043B\u0438\u0441", nameEn: "Ouranoupoli", priceEur: "180 \u20AC" }
    ]
  },
  {
    id: "serbia",
    nameKey: "destinationsPage.serbia",
    isForeign: true,
    destinations: [
      { nameMk: "\u0411\u0435\u043B\u0433\u0440\u0430\u0434", nameEn: "Belgrade", priceEur: "370 \u20AC" },
      { nameMk: "\u0412\u0440\u0430\u045A\u0435", nameEn: "Vranje", priceEur: "140 \u20AC" },
      { nameMk: "\u0412\u043B\u0430\u0434\u0438\u0447\u0438\u043D \u0425\u0430\u043D", nameEn: "Vladicin Han", priceEur: "150 \u20AC" },
      { nameMk: "\u0408\u0430\u0433\u043E\u0434\u0438\u043D\u0430", nameEn: "Jagodina", priceEur: "240 \u20AC" },
      { nameMk: "\u041A\u0440\u0443\u0448\u0435\u0432\u0430\u0446", nameEn: "Krusevac", priceEur: "240 \u20AC" },
      { nameMk: "\u041B\u0435\u0441\u043A\u043E\u0432\u0430\u0446", nameEn: "Leskovac", priceEur: "170 \u20AC" },
      { nameMk: "\u041D\u0438\u0448", nameEn: "Nis", priceEur: "190 \u20AC" },
      { nameMk: "\u041D\u043E\u0432\u0438 \u0421\u0430\u0434", nameEn: "Novi Sad", priceEur: "400 \u20AC" }
    ]
  },
  {
    id: "albania",
    nameKey: "destinationsPage.albania",
    isForeign: true,
    destinations: [
      { nameMk: "\u0412\u0430\u043B\u043E\u043D\u0430", nameEn: "Vlora", priceEur: "170 \u20AC" },
      { nameMk: "\u0414\u0440\u0430\u0447", nameEn: "Durres", priceEur: "160 \u20AC" },
      { nameMk: "\u0415\u043B\u0431\u0430\u0441\u0430\u043D", nameEn: "Elbasan", priceEur: "100 \u20AC" },
      { nameMk: "\u041A\u043E\u0440\u0447\u0430", nameEn: "Korca", priceEur: "70 \u20AC" },
      { nameMk: "\u041A\u0441\u0430\u043C\u0438\u043B", nameEn: "Ksamil", priceEur: "240 \u20AC" },
      { nameMk: "\u041F\u043E\u0433\u0440\u0430\u0434\u0435\u0446", nameEn: "Pogradec", priceEur: "70 \u20AC" },
      { nameMk: "\u0421\u0430\u0440\u0430\u043D\u0434\u0430", nameEn: "Saranda", priceEur: "240 \u20AC" },
      { nameMk: "\u0421\u043A\u0430\u0434\u0430\u0440", nameEn: "Shkoder", priceEur: "230 \u20AC" },
      { nameMk: "\u0421\u043F\u0438\u043B\u0435", nameEn: "Spille", priceEur: "150 \u20AC" },
      { nameMk: "\u0422\u0438\u0440\u0430\u043D\u0430", nameEn: "Tirana", priceEur: "150 \u20AC" }
    ]
  },
  {
    id: "bulgaria",
    nameKey: "destinationsPage.bulgaria",
    isForeign: true,
    destinations: [
      { nameMk: "\u0411\u0430\u043D\u0441\u043A\u043E", nameEn: "Bansko", priceEur: "180 \u20AC" },
      { nameMk: "\u0411\u043B\u0430\u0433\u043E\u0435\u0432\u0433\u0440\u0430\u0434", nameEn: "Blagoevgrad", priceEur: "170 \u20AC" },
      { nameMk: "\u0412\u0430\u0440\u043D\u0430", nameEn: "Varna", priceEur: "650 \u20AC" },
      { nameMk: "\u0414\u0443\u043F\u043D\u0438\u0446\u0430", nameEn: "Dupnitsa", priceEur: "180 \u20AC" },
      { nameMk: "\u0421\u0430\u043D\u0434\u0430\u043D\u0441\u043A\u0438", nameEn: "Sandanski", priceEur: "170 \u20AC" },
      { nameMk: "\u0421\u043E\u0444\u0438\u0458\u0430", nameEn: "Sofia", priceEur: "250 \u20AC" },
      { nameMk: "\u041A\u0443\u0441\u0442\u0435\u043D\u0434\u0438\u043B", nameEn: "Kyustendil", priceEur: "170 \u20AC" }
    ]
  },
  {
    id: "croatia",
    nameKey: "destinationsPage.croatia",
    isForeign: true,
    destinations: [
      { nameMk: "\u0417\u0430\u0433\u0440\u0435\u0431", nameEn: "Zagreb", priceEur: "500 \u20AC" },
      { nameMk: "\u0421\u043F\u043B\u0438\u0442", nameEn: "Split", priceEur: "650 \u20AC" },
      { nameMk: "\u0414\u0443\u0431\u0440\u043E\u0432\u043D\u0438\u043A", nameEn: "Dubrovnik", priceEur: "550 \u20AC" }
    ]
  },
  {
    id: "montenegro",
    nameKey: "destinationsPage.montenegro",
    isForeign: true,
    destinations: [
      { nameMk: "\u0411\u0443\u0434\u0432\u0430", nameEn: "Budva", priceEur: "320 \u20AC" },
      { nameMk: "\u041C\u0430\u043D\u0430\u0441\u0442\u0438\u0440 \u041E\u0441\u0442\u0440\u043E\u0433", nameEn: "Ostrog Monastery", priceEur: "330 \u20AC" },
      { nameMk: "\u041F\u043E\u0434\u0433\u043E\u0440\u0438\u0446\u0430", nameEn: "Podgorica", priceEur: "300 \u20AC" }
    ]
  },
  {
    id: "kosovo",
    nameKey: "destinationsPage.kosovo",
    isForeign: true,
    destinations: [
      { nameMk: "\u0403\u0438\u043B\u0430\u043D\u0435", nameEn: "Gjilan", priceEur: "160 \u20AC" },
      { nameMk: "\u041F\u0440\u0438\u0448\u0442\u0438\u043D\u0430", nameEn: "Pristina", priceEur: "150 \u20AC" }
    ]
  },
  {
    id: "tourist",
    nameKey: "destinationsPage.tourist",
    isForeign: false,
    destinations: [
      { nameMk: "\u0411\u0438\u0433\u043E\u0440\u0441\u043A\u0438 \u041C\u0430\u043D\u0430\u0441\u0442\u0438\u0440", nameEn: "Bigorski Monastery", priceMkd: "4500 \u0434\u0435\u043D", priceEur: "73 \u20AC" },
      { nameMk: "\u0413\u043E\u043B\u0435\u043C\u0430 \u041B\u0438\u0432\u0430\u0434\u0430", nameEn: "Golema Livada", priceMkd: "700 \u0434\u0435\u043D", priceEur: "12 \u20AC" },
      { nameMk: "\u0413\u0440\u0430\u0434\u0438\u0448\u0442\u0435 \u041E\u0445\u0440\u0438\u0434", nameEn: "Gradiste Ohrid", priceMkd: "3300 \u0434\u0435\u043D", priceEur: "55 \u20AC" },
      { nameMk: "\u0414\u0435\u0431\u0430\u0440\u0441\u043A\u0438 \u0411\u0430\u045A\u0438", nameEn: "Debar Spa", priceMkd: "4900 \u0434\u0435\u043D", priceEur: "80 \u20AC" },
      { nameMk: "\u0414\u0435\u0442\u0441\u043A\u043E\u0442\u043E \u041F\u0435\u043B\u0438\u0441\u0442\u0435\u0440", nameEn: "Pelister Children's Resort", priceMkd: "700 \u0434\u0435\u043D", priceEur: "12 \u20AC" },
      { nameMk: "\u041A\u043E\u045A\u0430\u0440\u043A\u0430 (\u0438\u0437\u043B\u0435\u0442)", nameEn: "Konjarka (excursion)", priceMkd: "1300 \u0434\u0435\u043D", priceEur: "21 \u20AC" },
      { nameMk: "\u041A\u0440\u0441\u0442\u043E\u0430\u0440 \u041C\u0430\u043D\u0430\u0441\u0442\u0438\u0440", nameEn: "Krstoar Monastery", priceMkd: "300 \u0434\u0435\u043D", priceEur: "5 \u20AC" },
      { nameMk: "\u041C\u0430\u0432\u0440\u043E\u0432\u043E", nameEn: "Mavrovo", priceMkd: "4300 \u0434\u0435\u043D", priceEur: "70 \u20AC" },
      { nameMk: "\u041C\u0430\u043B\u0430 \u041B\u0438\u0432\u0430\u0434\u0430", nameEn: "Mala Livada", priceMkd: "700 \u0434\u0435\u043D", priceEur: "12 \u20AC" },
      { nameMk: "\u041C\u043E\u043B\u0438\u043A\u0430", nameEn: "Molika", priceMkd: "800 \u0434\u0435\u043D", priceEur: "13 \u20AC" },
      { nameMk: "\u041D\u0435\u0433\u043E\u0440\u0441\u043A\u0438 \u0411\u0430\u045A\u0438", nameEn: "Negorski Spa", priceMkd: "5500 \u0434\u0435\u043D", priceEur: "90 \u20AC" },
      { nameMk: "\u041F\u043E\u043F\u043E\u0432\u0430 \u0428\u0430\u043F\u043A\u0430", nameEn: "Popova Shapka", priceMkd: "5500 \u0434\u0435\u043D", priceEur: "90 \u20AC" },
      { nameMk: "\u0421\u0432\u0435\u0442\u0438 \u041D\u0430\u0443\u043C", nameEn: "St. Naum", priceMkd: "3800 \u0434\u0435\u043D", priceEur: "62 \u20AC" }
    ]
  },
  {
    id: "cities",
    nameKey: "destinationsPage.cities",
    isForeign: false,
    destinations: [
      { nameMk: "\u0411\u0435\u0440\u043E\u0432\u043E", nameEn: "Berovo", priceMkd: "6800 \u0434\u0435\u043D", priceEur: "110 \u20AC" },
      { nameMk: "\u0411\u043E\u0433\u0434\u0430\u043D\u0446\u0438", nameEn: "Bogdanci", priceMkd: "5300 \u0434\u0435\u043D", priceEur: "86 \u20AC" },
      { nameMk: "\u0412\u0430\u043B\u0430\u043D\u0434\u043E\u0432\u043E", nameEn: "Valandovo", priceMkd: "5000 \u0434\u0435\u043D", priceEur: "81 \u20AC" },
      { nameMk: "\u0412\u0435\u043B\u0435\u0441", nameEn: "Veles", priceMkd: "4000 \u0434\u0435\u043D", priceEur: "65 \u20AC" },
      { nameMk: "\u0412\u0438\u043D\u0438\u0446\u0430", nameEn: "Vinica", priceMkd: "5800 \u0434\u0435\u043D", priceEur: "94 \u20AC" },
      { nameMk: "\u0413\u0435\u0432\u0433\u0435\u043B\u0438\u0458\u0430", nameEn: "Gevgelija", priceMkd: "5800 \u0434\u0435\u043D", priceEur: "94 \u20AC" },
      { nameMk: "\u0413\u043E\u0441\u0442\u0438\u0432\u0430\u0440", nameEn: "Gostivar", priceMkd: "4200 \u0434\u0435\u043D", priceEur: "68 \u20AC" },
      { nameMk: "\u0414\u0435\u0431\u0430\u0440", nameEn: "Debar", priceMkd: "4700 \u0434\u0435\u043D", priceEur: "76 \u20AC" },
      { nameMk: "\u0414\u0435\u043B\u0447\u0435\u0432\u043E", nameEn: "Delcevo", priceMkd: "6800 \u0434\u0435\u043D", priceEur: "110 \u20AC" },
      { nameMk: "\u0414\u0435\u043C\u0438\u0440 \u041A\u0430\u043F\u0438\u0458\u0430", nameEn: "Demir Kapija", priceMkd: "4000 \u0434\u0435\u043D", priceEur: "65 \u20AC" },
      { nameMk: "\u0414\u0435\u043C\u0438\u0440 \u0425\u0438\u0441\u0430\u0440", nameEn: "Demir Hisar", priceMkd: "900 \u0434\u0435\u043D", priceEur: "15 \u20AC" },
      { nameMk: "\u0414\u043E\u0458\u0440\u0430\u043D", nameEn: "Dojran", priceMkd: "5700 \u0434\u0435\u043D", priceEur: "93 \u20AC" },
      { nameMk: "\u041A\u0430\u0432\u0430\u0434\u0430\u0440\u0446\u0438", nameEn: "Kavadarci", priceMkd: "3200 \u0434\u0435\u043D", priceEur: "52 \u20AC" },
      { nameMk: "\u041A\u0438\u0447\u0435\u0432\u043E", nameEn: "Kicevo", priceMkd: "3000 \u0434\u0435\u043D", priceEur: "49 \u20AC" },
      { nameMk: "\u041A\u043E\u0447\u0430\u043D\u0438", nameEn: "Kocani", priceMkd: "5800 \u0434\u0435\u043D", priceEur: "94 \u20AC" },
      { nameMk: "\u041A\u0440\u0430\u0442\u043E\u0432\u043E", nameEn: "Kratovo", priceMkd: "6300 \u0434\u0435\u043D", priceEur: "102 \u20AC" },
      { nameMk: "\u041A\u0440\u0438\u0432\u0430 \u041F\u0430\u043B\u0430\u043D\u043A\u0430", nameEn: "Kriva Palanka", priceMkd: "6800 \u0434\u0435\u043D", priceEur: "110 \u20AC" },
      { nameMk: "\u041A\u0440\u0443\u0448\u0435\u0432\u043E", nameEn: "Krusevo", priceMkd: "2000 \u0434\u0435\u043D", priceEur: "32 \u20AC" },
      { nameMk: "\u041A\u0443\u043C\u0430\u043D\u043E\u0432\u043E", nameEn: "Kumanovo", priceMkd: "6000 \u0434\u0435\u043D", priceEur: "97 \u20AC" },
      { nameMk: "\u041C\u0430\u043A\u0435\u0434\u043E\u043D\u0441\u043A\u0430 \u041A\u0430\u043C\u0435\u043D\u0438\u0446\u0430", nameEn: "Makedonska Kamenica", priceMkd: "6300 \u0434\u0435\u043D", priceEur: "102 \u20AC" },
      { nameMk: "\u041C\u0430\u043A\u0435\u0434\u043E\u043D\u0441\u043A\u0438 \u0411\u0440\u043E\u0434", nameEn: "Makedonski Brod", priceMkd: "3000 \u0434\u0435\u043D", priceEur: "49 \u20AC" },
      { nameMk: "\u041D\u0435\u0433\u043E\u0442\u0438\u043D\u043E", nameEn: "Negotino", priceMkd: "3500 \u0434\u0435\u043D", priceEur: "57 \u20AC" },
      { nameMk: "\u041E\u0445\u0440\u0438\u0434", nameEn: "Ohrid", priceMkd: "2800 \u0434\u0435\u043D", priceEur: "45 \u20AC" },
      { nameMk: "\u041F\u0435\u0445\u0447\u0435\u0432\u043E", nameEn: "Pehcevo", priceMkd: "6800 \u0434\u0435\u043D", priceEur: "110 \u20AC" },
      { nameMk: "\u041F\u0440\u0438\u043B\u0435\u043F", nameEn: "Prilep", priceMkd: "1400 \u0434\u0435\u043D", priceEur: "23 \u20AC" },
      { nameMk: "\u041F\u0440\u043E\u0431\u0438\u0448\u0442\u0438\u043F", nameEn: "Probistip", priceMkd: "5800 \u0434\u0435\u043D", priceEur: "94 \u20AC" },
      { nameMk: "\u0420\u0430\u0434\u043E\u0432\u0438\u0448", nameEn: "Radovis", priceMkd: "5800 \u0434\u0435\u043D", priceEur: "94 \u20AC" },
      { nameMk: "\u0420\u0435\u0441\u0435\u043D", nameEn: "Resen", priceMkd: "1300 \u0434\u0435\u043D", priceEur: "21 \u20AC" },
      { nameMk: "\u0421\u0432\u0435\u0442\u0438 \u041D\u0438\u043A\u043E\u043B\u0435", nameEn: "Sveti Nikole", priceMkd: "4800 \u0434\u0435\u043D", priceEur: "78 \u20AC" },
      { nameMk: "\u0421\u043A\u043E\u043F\u0458\u0435", nameEn: "Skopje", priceMkd: "6300 \u0434\u0435\u043D", priceEur: "102 \u20AC" },
      { nameMk: "\u0421\u0442\u0440\u0443\u0433\u0430", nameEn: "Struga", priceMkd: "3300 \u0434\u0435\u043D", priceEur: "54 \u20AC" },
      { nameMk: "\u0421\u0442\u0440\u0443\u043C\u0438\u0446\u0430", nameEn: "Strumica", priceMkd: "5800 \u0434\u0435\u043D", priceEur: "94 \u20AC" },
      { nameMk: "\u0422\u0435\u0442\u043E\u0432\u043E", nameEn: "Tetovo", priceMkd: "5000 \u0434\u0435\u043D", priceEur: "81 \u20AC" },
      { nameMk: "\u0428\u0442\u0438\u043F", nameEn: "Stip", priceMkd: "4800 \u0434\u0435\u043D", priceEur: "78 \u20AC" }
    ]
  }
];

// src/lib/mcp/tools/get-destinations.ts
var get_destinations_default = defineTool({
  name: "get_destinations",
  title: "Get Destinations",
  description: "List LuxTaxi destinations and one-way prices from Bitola, grouped by category (airports, borders, Greece, Serbia, Albania, Bulgaria, Croatia, Montenegro, Kosovo, tourist spots, Macedonian cities).",
  inputSchema: {
    category: z.enum(["all", "airports", "borders", "greece", "serbia", "albania", "bulgaria", "croatia", "montenegro", "kosovo", "tourist", "cities"]).default("all").describe("Filter by destination category."),
    search: z.string().optional().describe("Optional case-insensitive search term for destination name.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, search }) => {
    let categories = category === "all" ? destinationCategories : destinationCategories.filter((c) => c.id === category);
    if (search?.trim()) {
      const term = search.trim().toLowerCase();
      categories = categories.map((c) => ({ ...c, destinations: c.destinations.filter((d) => d.nameEn.toLowerCase().includes(term) || d.nameMk.toLowerCase().includes(term)) })).filter((c) => c.destinations.length > 0);
    }
    return {
      content: [{ type: "text", text: JSON.stringify(categories, null, 2) }],
      structuredContent: { categories }
    };
  }
});

// src/lib/mcp/tools/get-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.1";

// src/lib/mcp/data/services.ts
var services = [
  {
    id: "vip",
    titleKey: "servicesPage.vip.title",
    descriptionKey: "servicesPage.vip.description",
    featureKeys: [
      "servicesPage.vip.feature1",
      "servicesPage.vip.feature2",
      "servicesPage.vip.feature3",
      "servicesPage.vip.feature4",
      "servicesPage.vip.feature5"
    ]
  },
  {
    id: "corporate",
    titleKey: "servicesPage.corporate.title",
    descriptionKey: "servicesPage.corporate.description",
    featureKeys: [
      "servicesPage.corporate.feature1",
      "servicesPage.corporate.feature2",
      "servicesPage.corporate.feature3",
      "servicesPage.corporate.feature4",
      "servicesPage.corporate.feature5"
    ]
  },
  {
    id: "delegations",
    titleKey: "servicesPage.delegations.title",
    descriptionKey: "servicesPage.delegations.description",
    featureKeys: [
      "servicesPage.delegations.feature1",
      "servicesPage.delegations.feature2",
      "servicesPage.delegations.feature3",
      "servicesPage.delegations.feature4",
      "servicesPage.delegations.feature5"
    ]
  },
  {
    id: "airport",
    titleKey: "servicesPage.airport.title",
    descriptionKey: "servicesPage.airport.description",
    featureKeys: [
      "servicesPage.airport.feature1",
      "servicesPage.airport.feature2",
      "servicesPage.airport.feature3",
      "servicesPage.airport.feature4",
      "servicesPage.airport.feature5"
    ]
  }
];

// src/lib/mcp/tools/get-services.ts
var get_services_default = defineTool2({
  name: "get_services",
  title: "Get Services",
  description: "List the taxi services offered by LuxTaxi: VIP transfers, corporate transport, delegations, and airport transfers.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
    structuredContent: { services }
  })
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.1";

// src/lib/mcp/data/contact.ts
var contactInfo = [
  {
    type: "phone",
    label: "Phone",
    value: "+389 75 269 459",
    url: "tel:+38975269459"
  },
  {
    type: "viber",
    label: "Viber",
    value: "+389 75 269 459",
    url: "viber://chat?number=%2B38975269459"
  },
  {
    type: "whatsapp",
    label: "WhatsApp",
    value: "+389 75 269 459",
    url: "https://wa.me/38975269459"
  },
  {
    type: "email",
    label: "Email",
    value: "info@luxtaxi.mk",
    url: "mailto:info@luxtaxi.mk"
  },
  {
    type: "location",
    label: "Location",
    value: "Bitola, Macedonia"
  }
];
var businessInfo = {
  name: "LuxTaxi \u0411\u0438\u0442\u043E\u043B\u0430",
  tagline: "\u0412\u0430\u0448\u0438\u043E\u0442 \u043F\u0430\u0440\u0442\u043D\u0435\u0440 \u0432\u043E \u043F\u0430\u0442\u0443\u0432\u0430\u045A\u0435\u0442\u043E",
  workingHours: "24/7",
  fleet: "VW Passat",
  baseLocation: "Bitola, Macedonia"
};

// src/lib/mcp/tools/get-contact-info.ts
var get_contact_info_default = defineTool3({
  name: "get_contact_info",
  title: "Get Contact Info",
  description: "Return LuxTaxi contact methods (phone, Viber, WhatsApp, email), location, fleet, and working hours.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify({ business: businessInfo, contact: contactInfo }, null, 2) }],
    structuredContent: { business: businessInfo, contact: contactInfo }
  })
});

// src/lib/mcp/tools/get-reviews.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z2 } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-reviews.ts
var get_reviews_default = defineTool4({
  name: "get_reviews",
  title: "Get Reviews",
  description: "Fetch approved public reviews left by LuxTaxi customers, ordered newest first.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).default(20).describe("Maximum number of reviews to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.from("public_reviews").select("*").order("created_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { reviews: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/submit-review.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z3 } from "npm:zod@^3.25.76";
var submit_review_default = defineTool5({
  name: "submit_review",
  title: "Submit Review",
  description: "Submit a customer review for LuxTaxi. Requires authentication; the review is recorded with the signed-in user's identity.",
  inputSchema: {
    rating: z3.number().int().min(1).max(5).describe("Star rating from 1 to 5."),
    comment: z3.string().trim().min(5).max(1e3).describe("Review comment."),
    name: z3.string().trim().min(2).max(100).optional().describe("Optional display name. Defaults to the signed-in user's first name if available.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ rating, comment, name }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated. Please connect your LuxTaxi account first." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const displayName = name?.trim() || ctx.getUserEmail()?.split("@")[0] || "LuxTaxi User";
    const { data, error } = await supabase.from("reviews").insert({
      rating,
      comment: comment.trim(),
      name: displayName,
      email: ctx.getUserEmail(),
      is_anonymous: false
    }).select();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: "Review submitted successfully." }],
      structuredContent: { review: data?.[0] }
    };
  }
});

// src/lib/mcp/tools/submit-contact-inquiry.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z4 } from "npm:zod@^3.25.76";
var submit_contact_inquiry_default = defineTool6({
  name: "submit_contact_inquiry",
  title: "Submit Contact Inquiry",
  description: "Send a ride inquiry or message to LuxTaxi via the contact form. Requires authentication.",
  inputSchema: {
    name: z4.string().trim().min(2).max(100).describe("Full name of the person making the inquiry."),
    phone: z4.string().trim().min(6).max(20).describe("Contact phone number."),
    destination: z4.string().trim().max(200).optional().describe("Desired destination or route."),
    date: z4.string().max(50).optional().describe("Desired travel date."),
    message: z4.string().trim().min(10).max(2e3).describe("Inquiry details.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ name, phone, destination, date, message }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated. Please connect your LuxTaxi account first." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.functions.invoke("send-contact-email", {
      body: {
        name: name.trim(),
        email: ctx.getUserEmail() || "",
        phone: phone.trim(),
        destination: destination?.trim() || "",
        date: date?.trim() || "",
        message: message.trim(),
        website: ""
      }
    });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: "Inquiry sent successfully. LuxTaxi will contact you soon." }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bafsspfgqaiqjbxqalfy";
var mcp_default = defineMcp({
  name: "luxtaxi-balkan-journeys",
  title: "LuxTaxi Balkan Journeys",
  version: "0.1.0",
  instructions: "Tools for LuxTaxi \u0411\u0438\u0442\u043E\u043B\u0430 \u2014 a premium taxi service based in Bitola, Macedonia. Use get_destinations and get_services for pricing and offerings, get_contact_info for contact methods, get_reviews for customer feedback, and submit_contact_inquiry / submit_review when the user wants to act through their LuxTaxi account.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_destinations_default,
    get_services_default,
    get_contact_info_default,
    get_reviews_default,
    submit_review_default,
    submit_contact_inquiry_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
